shopware:
  auto_update:
    # Disables the auto updater in the UI
    enabled: false
  admin_worker:
    enable_admin_worker: false
  mail:
    update_mail_variables_on_send: false
  html_sanitizer:
    enabled: false