<?php

declare(strict_types=1);

namespace FULLHAUS\MerchantFinder;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Plugin;
use Shopware\Core\Framework\Plugin\Context\InstallContext;
use Shopware\Core\Framework\Plugin\Context\UninstallContext;

class FhMerchantFinder extends Plugin
{
    private static $_defaults = [
        'allowedSearchCountryCodes' => ['de', 'at', 'ch'],
        'nominatim' => 'https://nominatim.openstreetmap.org/search.php',
    ];

    public static function getDefault($key)
    {
        return self::$_defaults[$key];
    }

    public function install(InstallContext $installContext): void
    {
        parent::install($installContext); // TODO: Change the autogenerated stuff
    }

    public function uninstall(UninstallContext $uninstallContext): void
    {
        parent::uninstall($uninstallContext);
        if ($uninstallContext->keepUserData()) {
            return;
        }
        $connection = $this->container->get(Connection::class);
        $connection->executeUpdate('DROP TABLE IF EXISTS `fh_merchant`');
        $connection->executeUpdate('DROP TABLE IF EXISTS `fh_zipcode`');
    }

    public function getStorefrontScriptPath(): string
    {
        return 'Resources/storefront/dist/storefront/js';
    }
}
